### ISSUE TITLE
@Flip doesn't work after upgrading to spring boot 1.4

### ISSUE THREAD

**Issue by tonybo2006** [clun/ff4j#188]
Spring boot 1.4 default to cglib proxy if the @Transacational was used. But FF4J use JdkDynamicAopProxy.

**Comment by tonybo2006** [comment]
![image](https://cloud.githubusercontent.com/assets/6345842/22971422/92bd6fb8-f3b0-11e6-8dd1-c900935f9112.png)

**Comment by clun** [comment]
From 1.6.1 it should be ok. Which version do you used ?

**Comment by tonybo2006** [comment]
verison is 1.6.2.

And I checked the source of FeatureAutoProxy.java. it seems there isn't change.

![image](https://cloud.githubusercontent.com/assets/6345842/23054310/23585e2e-f51a-11e6-99f2-18003d5210ee.png)

**Comment by clun** [comment]
Really want to help here. Took another pass on ff4j-aop, still not spotting the problem

The FeatureAopProxy do not use the `AopProxyUtils.utilmateTargetClass(beanClass)` during classpath scanning because *the cglib proxies are created later*. We can check objects to be enhanced with cglib after they have been initialized not as a class.

At runtime it retrieves the target object if cglib enhanced as expected [here](https://github.com/clun/ff4j/blob/master/ff4j-aop/src/main/java/org/ff4j/aop/FeatureAdvisor.java#L172)

I created a sample using Hystrix telling it works with cglib [SAMPLE](https://github.com/clun/ff4j-samples/tree/master/ff4j-sample-hystrix) I use the annotation [HERE](https://github.com/clun/ff4j-samples/blob/master/ff4j-sample-hystrix/src/main/java/org/ff4j/sample/integration/MyIntegrationImpl.java#L14).

Could you please help me reproduce the issue with a small code sample?

**Comment by clun** [comment]
I will create a sample with spring boot 1.4

**Comment by clun** [comment]
Still open ? Can I close ?
