### ISSUE TITLE
Maven central Artifact Java 1.6

### ISSUE THREAD

**Issue by nabilblk** [clun/ff4j#40]
Hi , 
The artifact in the Maven central are not java 1.6 compatible . 

How we can use ff4j with java 1.6 project , without compiling ff4j-core in local ?

Thanks in Advance

**Comment by clun** [comment]
Hi,

First, please note that JDK1.6 is no more supported since February 2013 and from this month (04/2015) only the JDK8 will be supported. http://www.oracle.com/technetwork/java/eol-135779.html

Yet i coded the ff4j to be compliant even with 1.5 (no lambda, no diamond operator, no AtomicXX object).  As a consequence, it's a matter of deployment). This a mistake during release. I will release a 1.3.1 compiled in 1.5. stay tuned.

**Comment by clun** [comment]
I release 1.3.1 with Java6 (JDK1.5 is really prehistoric now...)

**Comment by clun** [comment]
1.3.1 is now on central maven, compiled with 1.6. Let's close issue if resolved

**Comment by clun** [comment]
Tested on my desktop at work :)

**Comment by nabilblk** [comment]
Thanks
